/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vendor_android_blink_ledservice_LedServiceImpl */

#ifndef _Included_vendor_android_blink_ledservice_LedServiceImpl
#define _Included_vendor_android_blink_ledservice_LedServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vendor_android_blink_ledservice_LedServiceImpl
 * Method:    nativeLedON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vendor_android_1blink_ledservice_LedServiceImpl_nativeLedON
  (JNIEnv *, jclass);

/*
 * Class:     vendor_android_blink_ledservice_LedServiceImpl
 * Method:    nativeLedOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vendor_android_1blink_ledservice_LedServiceImpl_nativeLedOFF
  (JNIEnv *, jclass);

/*
 * Class:     vendor_android_blink_ledservice_LedServiceImpl
 * Method:    nativeUnexport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vendor_android_1blink_ledservice_LedServiceImpl_nativeUnexport
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
